/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.UI;

import com.project.Database.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafa
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        EditDatabase.setPreviousValue();
        panelSet();
    }
    public static void view(String fname,String uname,String phone,String mail,String pass){
       JfullName.setText(fname);
       JUserName.setText(uname);
       JPhone.setText(phone);
       JEmail.setText(mail);
       Jpassword1.setText(pass);
   }
public void panelSet(){
    HeadingPanel.setVisible(true);
        MenuPanel.setVisible(true);
        AboutPanel.setVisible(true);
        VictimSupportPanel.setVisible(false);
        PoliceNumberPanel.setVisible(false);
        AdminPanel.setVisible(false);
        SuspectPanel.setVisible(false);
        EditPanel.setVisible(false);
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeadingPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        VButton = new javax.swing.JButton();
        PButton = new javax.swing.JButton();
        Abutton = new javax.swing.JButton();
        EButton = new javax.swing.JButton();
        LButton = new javax.swing.JButton();
        ViewPanel = new javax.swing.JPanel();
        AboutPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        VictimSupportPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Vnid = new javax.swing.JTextField();
        Vphone = new javax.swing.JTextField();
        Vage = new javax.swing.JTextField();
        Vname = new javax.swing.JTextField();
        Vnationality = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        Vaddress = new javax.swing.JTextArea();
        VcrimeName = new javax.swing.JTextField();
        VcrimeTime = new javax.swing.JTextField();
        Vlocation = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Vdetails = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        SuspectPanel = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        Srelation = new javax.swing.JTextField();
        Sage = new javax.swing.JTextField();
        Sname = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        Smotive = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        Saddress = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        PoliceNumberPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        AdminPanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Pname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Pid = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Pbatch = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Pmobile = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        Pwork = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        Prank = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        EditPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JfullName = new javax.swing.JTextField();
        JUserName = new javax.swing.JTextField();
        JEmail = new javax.swing.JTextField();
        Jpassword1 = new javax.swing.JPasswordField();
        JPassword2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jMsg = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JPhone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bangladesh Police Help Desk");

        HeadingPanel.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 0));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/policelogo.jpg"))); // NOI18N
        jLabel6.setText("Bangladesh Police Help Desk");

        javax.swing.GroupLayout HeadingPanelLayout = new javax.swing.GroupLayout(HeadingPanel);
        HeadingPanel.setLayout(HeadingPanelLayout);
        HeadingPanelLayout.setHorizontalGroup(
            HeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadingPanelLayout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        HeadingPanelLayout.setVerticalGroup(
            HeadingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(HeadingPanel, java.awt.BorderLayout.PAGE_START);

        MenuPanel.setBackground(new java.awt.Color(255, 255, 204));
        MenuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 4, true), "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N

        VButton.setBackground(new java.awt.Color(255, 255, 204));
        VButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        VButton.setForeground(new java.awt.Color(102, 0, 0));
        VButton.setText("Victim Support");
        VButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VButtonActionPerformed(evt);
            }
        });

        PButton.setBackground(new java.awt.Color(255, 255, 204));
        PButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PButton.setForeground(new java.awt.Color(102, 0, 0));
        PButton.setText("Police Number");
        PButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PButtonActionPerformed(evt);
            }
        });

        Abutton.setBackground(new java.awt.Color(255, 255, 204));
        Abutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Abutton.setForeground(new java.awt.Color(102, 0, 0));
        Abutton.setText("Admin");
        Abutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbuttonActionPerformed(evt);
            }
        });

        EButton.setBackground(new java.awt.Color(255, 255, 204));
        EButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EButton.setForeground(new java.awt.Color(102, 0, 0));
        EButton.setText("Edit Profile");
        EButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EButtonActionPerformed(evt);
            }
        });

        LButton.setBackground(new java.awt.Color(255, 255, 204));
        LButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LButton.setForeground(new java.awt.Color(102, 0, 0));
        LButton.setText("Log Out");
        LButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VButton, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
            .addComponent(PButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Abutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(VButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Abutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(EButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        getContentPane().add(MenuPanel, java.awt.BorderLayout.LINE_START);

        ViewPanel.setLayout(new java.awt.CardLayout());

        AboutPanel.setBackground(new java.awt.Color(255, 255, 204));
        AboutPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 4, true), "About", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("We are immensely pleased to heartily welcome all to the webpage of Bangladesh police.  Originally created to serve the interests of the colonial authority of the far past, Bangladesh Police, now imbued with the spirit of freedom and independence, has come through a paradigm shift and become the symbol of rule of law. The dawn of this new journey was our great war of liberation when, in response to the clarion call of Bangabandhu, father of the nation, the undaunted members of this force chose to be the vanguards of a life-staking armed resistance against the brutal aggression to our beloved motherland. Since then we have been changing everyday in every ways and today policing here is pro-people, proactive, community-oriented, technology based and sensitized to issues regarding human rights, gender and children. Particularly, in the last four and a half years Bangladesh police has undergone radical changes in terms of professional amelioration, capacity building and service delivery, thanks to the personal and initiatives of the Honorable prime Minister in this regard.  Today we are fully committed to upholding the rule of law and ensuring a society safe for all to live and work, pray and play, and for the democracy to prosper and flourish.  We are for the community. So our focus is on building stronger trust with the community, and we consider the responsible members of the community our most potential weapons in the battle against all sorts of chaos and criminality.  We believe Bangladesh police Webpage will open up a new avenue for us to reach our goal. We wish this webpage a grand success.");
        jTextArea1.setToolTipText("");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_police.jpg"))); // NOI18N

        javax.swing.GroupLayout AboutPanelLayout = new javax.swing.GroupLayout(AboutPanel);
        AboutPanel.setLayout(AboutPanelLayout);
        AboutPanelLayout.setHorizontalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        AboutPanelLayout.setVerticalGroup(
            AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AboutPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        ViewPanel.add(AboutPanel, "card2");

        VictimSupportPanel.setBackground(new java.awt.Color(255, 255, 204));
        VictimSupportPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 4, true), "Victim Support", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N
        VictimSupportPanel.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 0, 0));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_1rsz_2download.png"))); // NOI18N
        jLabel20.setText("Name");
        VictimSupportPanel.add(jLabel20);
        jLabel20.setBounds(18, 35, 67, 32);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 0, 0));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_1images.jpg"))); // NOI18N
        jLabel21.setText("Age");
        VictimSupportPanel.add(jLabel21);
        jLabel21.setBounds(18, 78, 67, 32);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 0, 0));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_phonelogo.png"))); // NOI18N
        jLabel22.setText("Phone/Mobile");
        VictimSupportPanel.add(jLabel22);
        jLabel22.setBounds(18, 128, 122, 32);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 0, 0));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_1rsz_icon.png"))); // NOI18N
        jLabel23.setText("NID/Passport");
        VictimSupportPanel.add(jLabel23);
        jLabel23.setBounds(21, 170, 119, 32);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 0, 0));
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_reg.png"))); // NOI18N
        jLabel24.setText("Nationality");
        VictimSupportPanel.add(jLabel24);
        jLabel24.setBounds(20, 220, 102, 32);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 0, 0));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_apply.jpg"))); // NOI18N
        jLabel25.setText("Address");
        VictimSupportPanel.add(jLabel25);
        jLabel25.setBounds(18, 288, 85, 32);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 0, 0));
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_crime.jpg"))); // NOI18N
        jLabel26.setText("Crime ");
        VictimSupportPanel.add(jLabel26);
        jLabel26.setBounds(20, 350, 74, 32);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 0, 0));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_crime.jpg"))); // NOI18N
        jLabel27.setText("Time");
        VictimSupportPanel.add(jLabel27);
        jLabel27.setBounds(20, 400, 64, 32);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 0, 0));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_crime.jpg"))); // NOI18N
        jLabel28.setText("Place");
        VictimSupportPanel.add(jLabel28);
        jLabel28.setBounds(20, 450, 67, 32);

        Vnid.setBackground(new java.awt.Color(255, 153, 153));
        VictimSupportPanel.add(Vnid);
        Vnid.setBounds(158, 172, 166, 30);

        Vphone.setBackground(new java.awt.Color(255, 153, 153));
        VictimSupportPanel.add(Vphone);
        Vphone.setBounds(158, 128, 166, 32);

        Vage.setBackground(new java.awt.Color(255, 153, 153));
        VictimSupportPanel.add(Vage);
        Vage.setBounds(158, 78, 166, 32);

        Vname.setBackground(new java.awt.Color(255, 153, 153));
        VictimSupportPanel.add(Vname);
        Vname.setBounds(158, 35, 166, 32);

        Vnationality.setBackground(new java.awt.Color(255, 153, 153));
        VictimSupportPanel.add(Vnationality);
        Vnationality.setBounds(160, 220, 166, 32);

        Vaddress.setBackground(new java.awt.Color(255, 153, 153));
        Vaddress.setColumns(20);
        Vaddress.setLineWrap(true);
        Vaddress.setRows(5);
        Vaddress.setWrapStyleWord(true);
        jScrollPane3.setViewportView(Vaddress);

        VictimSupportPanel.add(jScrollPane3);
        jScrollPane3.setBounds(160, 270, 166, 61);

        VcrimeName.setBackground(new java.awt.Color(255, 153, 153));
        VictimSupportPanel.add(VcrimeName);
        VcrimeName.setBounds(160, 350, 166, 32);

        VcrimeTime.setBackground(new java.awt.Color(255, 153, 153));
        VictimSupportPanel.add(VcrimeTime);
        VcrimeTime.setBounds(158, 398, 166, 30);

        Vlocation.setBackground(new java.awt.Color(255, 153, 153));
        VictimSupportPanel.add(Vlocation);
        Vlocation.setBounds(160, 450, 166, 31);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 0, 0));
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_crime.jpg"))); // NOI18N
        jLabel29.setText("Crime Details");
        VictimSupportPanel.add(jLabel29);
        jLabel29.setBounds(392, 35, 115, 32);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Vdetails.setBackground(new java.awt.Color(255, 153, 153));
        Vdetails.setColumns(20);
        Vdetails.setLineWrap(true);
        Vdetails.setRows(5);
        Vdetails.setWrapStyleWord(true);
        jScrollPane4.setViewportView(Vdetails);

        VictimSupportPanel.add(jScrollPane4);
        jScrollPane4.setBounds(350, 70, 210, 160);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/Writting.gif"))); // NOI18N
        VictimSupportPanel.add(jLabel30);
        jLabel30.setBounds(360, 260, 190, 140);

        jButton4.setBackground(new java.awt.Color(255, 255, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_login.png"))); // NOI18N
        jButton4.setText("Next");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        VictimSupportPanel.add(jButton4);
        jButton4.setBounds(420, 440, 120, 40);

        ViewPanel.add(VictimSupportPanel, "card3");

        SuspectPanel.setBackground(new java.awt.Color(255, 255, 204));
        SuspectPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 4, true), "Suspect Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 0, 0));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_1rsz_2download.png"))); // NOI18N
        jLabel31.setText("Name");

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 0, 0));
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_1images.jpg"))); // NOI18N
        jLabel32.setText("Age");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(102, 0, 0));
        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_reg.png"))); // NOI18N
        jLabel33.setText("Relationship");

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(102, 0, 0));
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_apply.jpg"))); // NOI18N
        jLabel34.setText("Motive");

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(102, 0, 0));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_apply.jpg"))); // NOI18N
        jLabel35.setText("Address");

        Srelation.setBackground(new java.awt.Color(255, 153, 153));

        Sage.setBackground(new java.awt.Color(255, 153, 153));
        Sage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SageActionPerformed(evt);
            }
        });

        Sname.setBackground(new java.awt.Color(255, 153, 153));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Smotive.setBackground(new java.awt.Color(255, 153, 153));
        Smotive.setColumns(20);
        Smotive.setLineWrap(true);
        Smotive.setRows(5);
        Smotive.setWrapStyleWord(true);
        jScrollPane5.setViewportView(Smotive);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        Saddress.setBackground(new java.awt.Color(255, 153, 153));
        Saddress.setColumns(20);
        Saddress.setLineWrap(true);
        Saddress.setRows(5);
        Saddress.setWrapStyleWord(true);
        jScrollPane6.setViewportView(Saddress);

        jButton5.setBackground(new java.awt.Color(255, 255, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_1rsz_edit.jpg"))); // NOI18N
        jButton5.setText("ADD More");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/susgif.gif"))); // NOI18N

        jButton6.setBackground(new java.awt.Color(255, 255, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_c.png"))); // NOI18N
        jButton6.setText("Done");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SuspectPanelLayout = new javax.swing.GroupLayout(SuspectPanel);
        SuspectPanel.setLayout(SuspectPanelLayout);
        SuspectPanelLayout.setHorizontalGroup(
            SuspectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuspectPanelLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(SuspectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SuspectPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6)
                        .addGap(51, 51, 51))
                    .addGroup(SuspectPanelLayout.createSequentialGroup()
                        .addGroup(SuspectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jLabel36)
                        .addGap(29, 29, 29))))
            .addGroup(SuspectPanelLayout.createSequentialGroup()
                .addGroup(SuspectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SuspectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(SuspectPanelLayout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jLabel32)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Sage, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(SuspectPanelLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(SuspectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel34)
                                .addGroup(SuspectPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel33)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Srelation, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel35))))
                    .addGroup(SuspectPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel31)
                        .addGap(55, 55, 55)
                        .addComponent(Sname, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        SuspectPanelLayout.setVerticalGroup(
            SuspectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SuspectPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(SuspectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(Sname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(SuspectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SuspectPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(SuspectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sage, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addGap(14, 14, 14)
                        .addGroup(SuspectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(Srelation, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(SuspectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SuspectPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SuspectPanelLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel34)))
                        .addGap(1, 1, 1)
                        .addGroup(SuspectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SuspectPanelLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel35))
                            .addGroup(SuspectPanelLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(SuspectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(SuspectPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        ViewPanel.add(SuspectPanel, "card4");

        PoliceNumberPanel.setBackground(new java.awt.Color(255, 204, 153));
        PoliceNumberPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 4, true), "Police Number \n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/call.gif"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 0, 0));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/policelogo.jpg"))); // NOI18N
        jLabel19.setText("Select Metropoliton");

        jComboBox2.setBackground(new java.awt.Color(255, 153, 51));
        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Dhaka Metropoliton", "Chottogram Metropoliton", "Khulna Metropoliton", "Rajhshahi Metropoliton", "Gajipur Metropoliton", "Others" }));

        jTable1.setBackground(new java.awt.Color(255, 153, 102));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Police ID", "Police Name", "Police Number", "Rank"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton7.setBackground(new java.awt.Color(255, 153, 102));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(102, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_back.jpg"))); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PoliceNumberPanelLayout = new javax.swing.GroupLayout(PoliceNumberPanel);
        PoliceNumberPanel.setLayout(PoliceNumberPanelLayout);
        PoliceNumberPanelLayout.setHorizontalGroup(
            PoliceNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PoliceNumberPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(PoliceNumberPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(PoliceNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PoliceNumberPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(88, 88, 88))
        );
        PoliceNumberPanelLayout.setVerticalGroup(
            PoliceNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PoliceNumberPanelLayout.createSequentialGroup()
                .addGroup(PoliceNumberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PoliceNumberPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PoliceNumberPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ViewPanel.add(PoliceNumberPanel, "card7");

        AdminPanel.setBackground(new java.awt.Color(153, 0, 51));
        AdminPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 204), 4, true), "Police Information Add", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 0))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 204));
        jLabel10.setText("Name");

        Pname.setBackground(new java.awt.Color(255, 255, 204));
        Pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PnameActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 204));
        jLabel11.setText("ID");

        Pid.setBackground(new java.awt.Color(255, 255, 204));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 204));
        jLabel12.setText("Batch no");

        Pbatch.setBackground(new java.awt.Color(255, 255, 204));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 204));
        jLabel13.setText("Mobile/Phone");

        Pmobile.setBackground(new java.awt.Color(255, 255, 204));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 204));
        jLabel14.setText("Work Station");

        Pwork.setBackground(new java.awt.Color(255, 255, 204));
        Pwork.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select One", "Dhaka Metropoliton", "Chottogram Metropoliton", "Khulna Metropoliton", "Rajhshahi Metropoliton", "Gajipur Metropoliton", "Others" }));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 204));
        jLabel15.setText("Rank");

        Prank.setBackground(new java.awt.Color(255, 255, 204));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/victim.gif"))); // NOI18N

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_c.png"))); // NOI18N
        jButton3.setText("Done");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(153, 0, 51));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_reg.png"))); // NOI18N
        jButton8.setText("Add More");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AdminPanelLayout.createSequentialGroup()
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Pbatch, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AdminPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Pid, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AdminPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Pmobile)
                                    .addComponent(Prank))))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AdminPanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(Pwork, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AdminPanelLayout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(187, 187, 187))
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdminPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pbatch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(Pmobile, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(Pwork, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(AdminPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(Prank, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton3))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        ViewPanel.add(AdminPanel, "card5");

        EditPanel.setBackground(new java.awt.Color(255, 255, 204));
        EditPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 3, true), "Edit Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 0, 0))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_1rsz_2download.png"))); // NOI18N
        jLabel1.setText("Full Name ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_1images.jpg"))); // NOI18N
        jLabel2.setText("User Name ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_1images.png"))); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 0));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_pass.jpg"))); // NOI18N
        jLabel4.setText("New Password ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_download_1.png"))); // NOI18N
        jLabel5.setText("Confirm Password ");

        JfullName.setBackground(new java.awt.Color(255, 153, 153));
        JfullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JfullNameActionPerformed(evt);
            }
        });

        JUserName.setEditable(false);
        JUserName.setBackground(new java.awt.Color(255, 153, 153));

        JEmail.setBackground(new java.awt.Color(255, 153, 153));
        JEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmailActionPerformed(evt);
            }
        });

        Jpassword1.setBackground(new java.awt.Color(255, 153, 153));

        JPassword2.setBackground(new java.awt.Color(255, 153, 153));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_apply.jpg"))); // NOI18N
        jButton1.setText("Apply ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMsg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMsg.setForeground(new java.awt.Color(0, 102, 102));
        jMsg.setText("If you Dont wanna change of any field, just leave it as it is.");

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_back.jpg"))); // NOI18N
        jButton2.setText("Back ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/ezgif.com-gif-maker (3).gif"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/project/picture/rsz_phonelogo.png"))); // NOI18N
        jLabel8.setText("Phone");

        JPhone.setBackground(new java.awt.Color(255, 153, 153));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("You can't change your User Name");

        javax.swing.GroupLayout EditPanelLayout = new javax.swing.GroupLayout(EditPanel);
        EditPanel.setLayout(EditPanelLayout);
        EditPanelLayout.setHorizontalGroup(
            EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Jpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(JEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addGap(63, 63, 63)
                        .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JfullName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
            .addGroup(EditPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(EditPanelLayout.createSequentialGroup()
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jMsg))
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EditPanelLayout.setVerticalGroup(
            EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JfullName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EditPanelLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Jpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(JPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(EditPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JEmail)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EditPanelLayout.createSequentialGroup()
                                .addComponent(JPhone)
                                .addGap(4, 4, 4)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addComponent(jMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(EditPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        ViewPanel.add(EditPanel, "card8");

        getContentPane().add(ViewPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JfullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JfullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JfullNameActionPerformed

    private void JEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JEmailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jMsg.setText("Profile has been Updated. :-). ");
       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void PnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PnameActionPerformed

    private void SageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SageActionPerformed

    private void VButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VButtonActionPerformed
        // TODO add your handling code here:
        HeadingPanel.setVisible(true);
        MenuPanel.setVisible(true);
        AboutPanel.setVisible(false);
        PoliceNumberPanel.setVisible(false);
        AdminPanel.setVisible(false);
        SuspectPanel.setVisible(false);
        EditPanel.setVisible(false);
         VictimSupportPanel.setVisible(true);
    }//GEN-LAST:event_VButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         HeadingPanel.setVisible(true);
        MenuPanel.setVisible(true);
        AboutPanel.setVisible(false);
        PoliceNumberPanel.setVisible(false);
        AdminPanel.setVisible(false);
        EditPanel.setVisible(false);
         VictimSupportPanel.setVisible(false);
         Sname.setText("");
         Sage.setText("");
         Srelation.setText("");
         Smotive.setText("");
         Saddress.setText("");
           SuspectPanel.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        panelSet();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(Vname.getText().isEmpty()|| Vphone.getText().isEmpty() || Vnationality.getText().isEmpty() || Vaddress.getText().isEmpty() || VcrimeName.getText().isEmpty() || VcrimeTime.getText().isEmpty() || Vlocation.getText().isEmpty() || Vdetails.getText().isEmpty())
        {
            HeadingPanel.setVisible(true);
        MenuPanel.setVisible(true);
        AboutPanel.setVisible(false);
        PoliceNumberPanel.setVisible(false);
        AdminPanel.setVisible(false);
        EditPanel.setVisible(false);
           SuspectPanel.setVisible(false);
           VictimSupportPanel.setVisible(true);
            JOptionPane.showMessageDialog(null,"Please Enter All information.");
        }
        else{
        HeadingPanel.setVisible(true);
        MenuPanel.setVisible(true);
        AboutPanel.setVisible(false);
        PoliceNumberPanel.setVisible(false);
        AdminPanel.setVisible(false);
        EditPanel.setVisible(false);
         VictimSupportPanel.setVisible(false);
           SuspectPanel.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void PButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PButtonActionPerformed
        // TODO add your handling code here:
        HeadingPanel.setVisible(true);
        MenuPanel.setVisible(true);
        AboutPanel.setVisible(false);
        AdminPanel.setVisible(false);
        EditPanel.setVisible(false);
         VictimSupportPanel.setVisible(false);
           SuspectPanel.setVisible(false);
         PoliceNumberPanel.setVisible(true);
    }//GEN-LAST:event_PButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        panelSet();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void AbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbuttonActionPerformed
        // TODO add your handling code here:
     this.dispose();
       new AdminCheck().setVisible(true);
    }//GEN-LAST:event_AbuttonActionPerformed

    private void EButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EButtonActionPerformed
        // TODO add your handling code here:
         HeadingPanel.setVisible(true);
        MenuPanel.setVisible(true);
        AboutPanel.setVisible(false);
      
         VictimSupportPanel.setVisible(false);
           SuspectPanel.setVisible(false);
         PoliceNumberPanel.setVisible(false);
         AdminPanel.setVisible(false);
           EditPanel.setVisible(true);
    }//GEN-LAST:event_EButtonActionPerformed

    private void LButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
          new HomePage().setVisible(true);
    }//GEN-LAST:event_LButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(Pname.getText().isEmpty() || Pbatch.getText().isEmpty() || Pwork.getSelectedIndex()==0 || Prank.getText().isEmpty() || Pmobile.getText().isEmpty() ){
            
            JOptionPane.showMessageDialog(null,"Give all input correctly.");
        }
        else
        {
            work=""+Pwork.getSelectedItem()+"";
        PoliceDatabase.PoliceInfo(Pname.getText(),Pbatch.getText(), work,Prank.getText(),Pmobile.getText());
        JOptionPane.showMessageDialog(null,"Data has been updated.");
        
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Pname.setText("");
        Pbatch.setText("");
        Pwork.setSelectedIndex(0);
        Prank.setText("");
        Pmobile.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
public void setVisibility(boolean c){
     if(c)
        { 
          new AdminCheck().dispose();
         HeadingPanel.setVisible(true);
        MenuPanel.setVisible(true);
        AboutPanel.setVisible(false);
        EditPanel.setVisible(false);
         VictimSupportPanel.setVisible(false);
           SuspectPanel.setVisible(false);
         PoliceNumberPanel.setVisible(false);
         AdminPanel.setVisible(true);
        }
        else{
            
            panelSet();
        }
}
private String work;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPanel;
    private javax.swing.JButton Abutton;
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JButton EButton;
    private javax.swing.JPanel EditPanel;
    private javax.swing.JPanel HeadingPanel;
    private static javax.swing.JTextField JEmail;
    private static javax.swing.JPasswordField JPassword2;
    private static javax.swing.JTextField JPhone;
    private static javax.swing.JTextField JUserName;
    private static javax.swing.JTextField JfullName;
    private static javax.swing.JPasswordField Jpassword1;
    private javax.swing.JButton LButton;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JButton PButton;
    private javax.swing.JTextField Pbatch;
    private javax.swing.JTextField Pid;
    private javax.swing.JTextField Pmobile;
    private javax.swing.JTextField Pname;
    private javax.swing.JPanel PoliceNumberPanel;
    private javax.swing.JTextField Prank;
    private javax.swing.JComboBox<String> Pwork;
    private javax.swing.JTextArea Saddress;
    private javax.swing.JTextField Sage;
    private javax.swing.JTextArea Smotive;
    private javax.swing.JTextField Sname;
    private javax.swing.JTextField Srelation;
    private javax.swing.JPanel SuspectPanel;
    private javax.swing.JButton VButton;
    private javax.swing.JTextArea Vaddress;
    private javax.swing.JTextField Vage;
    private javax.swing.JTextField VcrimeName;
    private javax.swing.JTextField VcrimeTime;
    private javax.swing.JTextArea Vdetails;
    private javax.swing.JPanel VictimSupportPanel;
    private javax.swing.JPanel ViewPanel;
    private javax.swing.JTextField Vlocation;
    private javax.swing.JTextField Vname;
    private javax.swing.JTextField Vnationality;
    private javax.swing.JTextField Vnid;
    private javax.swing.JTextField Vphone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jMsg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
